import { React.CSSProperties } from 'react';

export const styles: Record<string, React.CSSProperties> = {
  container: {
    padding: '24px',
    maxWidth: '1400px',
    margin: '0 auto',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '24px',
  },
  title: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#1f2937',
    margin: 0,
  },
  headerActions: {
    display: 'flex',
    alignItems: 'center',
    gap: '16px',
  },
  lastUpdate: {
    fontSize: '14px',
    color: '#6b7280',
  },
  refreshButton: {
    padding: '8px 16px',
    fontSize: '14px',
    fontWeight: '500',
    color: '#fff',
    backgroundColor: '#0066cc',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))',
    gap: '16px',
    marginBottom: '24px',
  },
  scheduleInfo: {
    display: 'flex',
    gap: '24px',
    padding: '16px 24px',
    backgroundColor: '#f0f9ff',
    border: '1px solid #bae6fd',
    borderRadius: '8px',
    marginBottom: '24px',
  },
  scheduleInfoItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  scheduleInfoLabel: {
    fontSize: '12px',
    color: '#0369a1',
    fontWeight: '500',
  },
  scheduleInfoValue: {
    fontSize: '18px',
    color: '#0c4a6e',
    fontWeight: '600',
  },
  statCard: {
    padding: '16px',
    backgroundColor: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: '8px',
    textAlign: 'center',
  },
  statValue: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '4px',
  },
  statLabel: {
    fontSize: '14px',
    color: '#6b7280',
  },
  listContainer: {
    backgroundColor: '#fff',
    border: '1px solid #e5e7eb',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  listHeader: {
    padding: '16px 24px',
    borderBottom: '1px solid #e5e7eb',
    backgroundColor: '#f9fafb',
  },
  listTitle: {
    fontSize: '18px',
    fontWeight: '600',
    color: '#1f2937',
    margin: 0,
  },
  taskItem: {
    padding: '16px 24px',
    borderBottom: '1px solid #e5e7eb',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
    backgroundColor: '#fff',
  },
  taskItemSelected: {
    backgroundColor: '#eff6ff',
  },
  taskHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: '12px',
  },
  taskTitle: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  taskName: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f2937',
  },
  taskType: {
    fontSize: '14px',
    color: '#6b7280',
  },
  taskMeta: {
    display: 'flex',
    gap: '8px',
  },
  priorityBadge: {
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#fff',
    borderRadius: '12px',
  },
  priorityControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    padding: '12px 16px',
    backgroundColor: '#f9fafb',
    border: '1px solid #e5e7eb',
    borderRadius: '6px',
    marginBottom: '12px',
  },
  priorityControlsLabel: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#374151',
  },
  priorityButtons: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  priorityButton: {
    width: '32px',
    height: '32px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: 'bold',
    color: '#fff',
    backgroundColor: '#0066cc',
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  priorityButtonDisabled: {
    backgroundColor: '#d1d5db',
    cursor: 'not-allowed',
  },
  priorityValue: {
    fontSize: '16px',
    fontWeight: '600',
    color: '#1f2937',
    minWidth: '24px',
    textAlign: 'center',
  },
  prioritySlider: {
    flex: 1,
    height: '6px',
    borderRadius: '3px',
    outline: 'none',
    cursor: 'pointer',
  },
  statusBadge: {
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#fff',
    borderRadius: '12px',
  },
  scheduledBadge: {
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#0066cc',
    backgroundColor: '#eff6ff',
    border: '1px solid #0066cc',
    borderRadius: '12px',
  },
  retryBadge: {
    padding: '4px 12px',
    fontSize: '12px',
    fontWeight: '600',
    color: '#f59e0b',
    backgroundColor: '#fffbeb',
    border: '1px solid #f59e0b',
    borderRadius: '12px',
  },
  retryInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    backgroundColor: '#eff6ff',
    border: '1px solid #93c5fd',
    borderRadius: '6px',
    marginBottom: '12px',
  },
  retryIcon: {
    fontSize: '16px',
  },
  retryText: {
    fontSize: '14px',
    color: '#1e40af',
    fontWeight: '500',
  },
  progressContainer: {
    position: 'relative',
    height: '24px',
    backgroundColor: '#e5e7eb',
    borderRadius: '4px',
    marginBottom: '12px',
    overflow: 'hidden',
  },
  progressBar: {
    height: '100%',
    backgroundColor: '#0066cc',
    transition: 'width 0.3s ease',
  },
  progressText: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    fontSize: '12px',
    fontWeight: '600',
    color: '#1f2937',
  },
  estimatedCompletionContainer: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    backgroundColor: '#f0f9ff',
    border: '1px solid #bae6fd',
    borderRadius: '6px',
    marginBottom: '12px',
  },
  estimatedCompletionLabel: {
    fontSize: '14px',
    color: '#0369a1',
    fontWeight: '500',
  },
  estimatedCompletionValue: {
    fontSize: '14px',
    color: '#0c4a6e',
    fontWeight: '600',
  },
  estimatedCompletionTime: {
    fontSize: '12px',
    color: '#0369a1',
  },
  taskDetails: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '8px',
    marginBottom: '8px',
  },
  taskDetailItem: {
    display: 'flex',
    gap: '8px',
    fontSize: '14px',
  },
  taskDetailLabel: {
    color: '#6b7280',
    fontWeight: '500',
  },
  taskDetailValue: {
    color: '#1f2937',
  },
  errorInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    backgroundColor: '#fef3c7',
    border: '1px solid #fbbf24',
    borderRadius: '6px',
    marginTop: '8px',
  },
  errorIcon: {
    fontSize: '16px',
  },
  errorMessage: {
    fontSize: '14px',
    color: '#92400e',
  },
  emptyState: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    textAlign: 'center',
  },
  emptyIcon: {
    fontSize: '64px',
    marginBottom: '16px',
  },
  emptyText: {
    fontSize: '16px',
    color: '#6b7280',
  },
  errorContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '60px 20px',
    textAlign: 'center',
  },
  errorTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: '8px',
  },
  retryButton: {
    padding: '12px 24px',
    fontSize: '16px',
    fontWeight: '500',
    color: '#fff',
    backgroundColor: '#0066cc',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  backgroundErrorBanner: {
    marginTop: '24px',
    padding: '12px 16px',
    backgroundColor: '#fef3c7',
    border: '1px solid #fbbf24',
    borderRadius: '6px',
    color: '#92400e',
    fontSize: '14px',
  },
};
